Repository Alkiiro/family-feud, pull requests merged in 2019-12, with the labels that each got.

#10 Class testing
  src/scripts/Survey.js
  test/game-test.js
  test/panicround-test.js
  test/player-test.js
  test/round-test.js
  test/survey-test.js
Labels: testing

#11 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: testing

#12 Class testing
  src/scripts/Player.js
  src/scripts/Survey.js
  test/player-test.js
  test/sample-test.js
  test/survey-test.js
Labels: bug fix, testing

#13 Css html styling
  .gitignore
  src/css/base.scss
  src/images/hallway-with-window.jpg
  src/index.html
  src/index.js
Labels: enhancement

#15 Css refactor2
  src/css/base.scss
  src/index.html
Labels: enhancement

#16 Game data
  src/index.js
  src/scripts/Game.js
  src/scripts/Survey.js
  test/game-test.js
  test/player-test.js
  test/survey-test.js
Labels: testing

#17 Dom manipulation
  src/css/base.scss
  src/index.html
  src/index.js
  src/scripts/domUpdates.js
Labels: enhancement
